### ISSUE TITLE
Columns are not arranged in a sequential manna

### ISSUE THREAD

**Issue by moloscripts** [dickoa/robotoolbox#2]
Columns of the data downloaded are not as sequentially arranged as in the ones in the koboToolbox survey. 
This proves difficult in renaming the columns based on the survey.

**Comment by dickoa** [comment]
Hi @moloscripts 
Thanks for the issue. You mean the order of the columns are different from the csv/excel exports ?

**Comment by dickoa** [comment]
@moloscripts 

I hope all is good. Can you expand? Or give me an example of the desired output?

**Comment by dickoa** [comment]
@moloscripts 
I'll close this issue, please re-open it if you it's working as expected.
